spring:
  application:
    name: dogsproject
  docker:
    compose:
      lifecycle-management: start_only
  datasource:
    username: myuser
    password: secret
    url: jdbc:postgresql://pgvector:5432/mydatabase
  sql:
    init:
      mode: always
